environment          = "prod"
project_name         = "myapp2-prod"
aws_region           = "us-east-1"
vpc_cidr             = "10.3.0.0/16"
instance_type        = "t3.large"
desired_size         = 1
min_size             = 1
max_size             = 5
private_subnet_cidrs = ["10.3.10.0/24", "10.3.11.0/24"]
