environment          = "qa"
project_name         = "myapp2-qa"
aws_region           = "us-east-1"
vpc_cidr             = "10.2.0.0/16"
instance_type        = "t3.medium"
desired_size         = 1
min_size             = 1
max_size             = 3
private_subnet_cidrs = ["10.2.10.0/24", "10.2.11.0/24"]
