#!/bin/bash
echo "Checking SonarQube workflow status..."
echo ""
echo "Repository: vegatros/q"
echo "Branch: b1"
echo "Commit: $(git rev-parse --short HEAD)"
echo ""
echo "Workflow file exists: $(test -f .github/workflows/sonarqube.yml && echo '✓ Yes' || echo '✗ No')"
echo "Sonar config exists: $(test -f sonar-project.properties && echo '✓ Yes' || echo '✗ No')"
echo ""
echo "View workflow runs at:"
echo "https://github.com/vegatros/q/actions/workflows/sonarqube.yml"
echo ""
echo "Latest commit pushed to trigger workflow."
