apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app7-qa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_ORG/YOUR_REPO.git
    targetRevision: main
    path: terraform/stacks/app7/helm/app-chart
    helm:
      valueFiles:
        - values.yaml
        - values-qa.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: app7-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
