replicaCount: 2
namespace: app7-qa

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

podDisruptionBudget:
  enabled: true
  minAvailable: 1
